
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "F:/Environment/cmake-3.26.3-windows-x86_64/share/cmake-3.26/Modules/CMakeDetermineSystem.cmake:204 (message)"
      - "CMakeLists.txt:30 (project)"
    message: |
      The system is: Windows - 10.0.19045 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "F:/Environment/cmake-3.26.3-windows-x86_64/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "F:/Environment/cmake-3.26.3-windows-x86_64/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "F:/Environment/cmake-3.26.3-windows-x86_64/share/cmake-3.26/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:30 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      MSBuild version 17.5.1+f6fdcf537 for .NET Framework
      빌드 시작: 2023-04-25 오후 12:41:27
      Included response file: F:\\Environment\\Microsoft Visual Studio\\2022\\MSBuild\\Current\\Bin\\amd64\\MSBuild.rsp
      
      1 노드의 "F:\\workspace\\tests\\ArtAuction\\ArtAuction\\proj.win32\\CMakeFiles\\3.26.3\\CompilerIdC\\CompilerIdC.vcxproj" 프로젝트(기본 대상)입니다.
      PrepareForBuild:
        "Debug\\" 디렉터리를 만들고 있습니다.
        "Debug\\CompilerIdC.tlog\\" 디렉터리를 만들고 있습니다.
      InitializeBuildStatus:
        "AlwaysCreate"이(가) 지정되었기 때문에 "Debug\\CompilerIdC.tlog\\unsuccessfulbuild"을(를) 만들고 있습니다.
      ClCompile:
        F:\\Environment\\Microsoft Visual Studio\\2022\\VC\\Tools\\MSVC\\14.35.32215\\bin\\HostX64\\x86\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /Oy- /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TC /analyze- /FC /errorReport:queue CMakeCCompilerId.c
        CMakeCCompilerId.c
      Link:
        F:\\Environment\\Microsoft Visual Studio\\2022\\VC\\Tools\\MSVC\\14.35.32215\\bin\\HostX64\\x86\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdC.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdC.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdC.lib" /MACHINE:X86 /SAFESEH Debug\\CMakeCCompilerId.obj
        CompilerIdC.vcxproj -> F:\\workspace\\tests\\ArtAuction\\ArtAuction\\proj.win32\\CMakeFiles\\3.26.3\\CompilerIdC\\CompilerIdC.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_C_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_C_COMPILER=F:\\Environment\\Microsoft Visual Studio\\2022\\VC\\Tools\\MSVC\\14.35.32215\\bin\\Hostx64\\x86\\cl.exe
      FinalizeBuildStatus:
        "Debug\\CompilerIdC.tlog\\unsuccessfulbuild" 파일을 삭제하고 있습니다.
        "Debug\\CompilerIdC.tlog\\CompilerIdC.lastbuildstate"에 연결(touching)하고 있습니다.
      "F:\\workspace\\tests\\ArtAuction\\ArtAuction\\proj.win32\\CMakeFiles\\3.26.3\\CompilerIdC\\CompilerIdC.vcxproj" 프로젝트를 빌드했습니다(기본 대상).
      
      빌드했습니다.
          경고 0개
          오류 0개
      
      경과 시간: 00:00:02.13
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.exe"
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.vcxproj"
      
      The C compiler identification is MSVC, found in:
        F:/workspace/tests/ArtAuction/ArtAuction/proj.win32/CMakeFiles/3.26.3/CompilerIdC/CompilerIdC.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "F:/Environment/cmake-3.26.3-windows-x86_64/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "F:/Environment/cmake-3.26.3-windows-x86_64/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "F:/Environment/cmake-3.26.3-windows-x86_64/share/cmake-3.26/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:30 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      MSBuild version 17.5.1+f6fdcf537 for .NET Framework
      빌드 시작: 2023-04-25 오후 12:41:29
      Included response file: F:\\Environment\\Microsoft Visual Studio\\2022\\MSBuild\\Current\\Bin\\amd64\\MSBuild.rsp
      
      1 노드의 "F:\\workspace\\tests\\ArtAuction\\ArtAuction\\proj.win32\\CMakeFiles\\3.26.3\\CompilerIdCXX\\CompilerIdCXX.vcxproj" 프로젝트(기본 대상)입니다.
      PrepareForBuild:
        "Debug\\" 디렉터리를 만들고 있습니다.
        "Debug\\CompilerIdCXX.tlog\\" 디렉터리를 만들고 있습니다.
      InitializeBuildStatus:
        "AlwaysCreate"이(가) 지정되었기 때문에 "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild"을(를) 만들고 있습니다.
      ClCompile:
        F:\\Environment\\Microsoft Visual Studio\\2022\\VC\\Tools\\MSVC\\14.35.32215\\bin\\HostX64\\x86\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /Oy- /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TP /analyze- /FC /errorReport:queue CMakeCXXCompilerId.cpp
        CMakeCXXCompilerId.cpp
      Link:
        F:\\Environment\\Microsoft Visual Studio\\2022\\VC\\Tools\\MSVC\\14.35.32215\\bin\\HostX64\\x86\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdCXX.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdCXX.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdCXX.lib" /MACHINE:X86 /SAFESEH Debug\\CMakeCXXCompilerId.obj
        CompilerIdCXX.vcxproj -> F:\\workspace\\tests\\ArtAuction\\ArtAuction\\proj.win32\\CMakeFiles\\3.26.3\\CompilerIdCXX\\CompilerIdCXX.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_CXX_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_CXX_COMPILER=F:\\Environment\\Microsoft Visual Studio\\2022\\VC\\Tools\\MSVC\\14.35.32215\\bin\\Hostx64\\x86\\cl.exe
      FinalizeBuildStatus:
        "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild" 파일을 삭제하고 있습니다.
        "Debug\\CompilerIdCXX.tlog\\CompilerIdCXX.lastbuildstate"에 연결(touching)하고 있습니다.
      "F:\\workspace\\tests\\ArtAuction\\ArtAuction\\proj.win32\\CMakeFiles\\3.26.3\\CompilerIdCXX\\CompilerIdCXX.vcxproj" 프로젝트를 빌드했습니다(기본 대상).
      
      빌드했습니다.
          경고 0개
          오류 0개
      
      경과 시간: 00:00:00.94
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.exe"
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.vcxproj"
      
      The CXX compiler identification is MSVC, found in:
        F:/workspace/tests/ArtAuction/ArtAuction/proj.win32/CMakeFiles/3.26.3/CompilerIdCXX/CompilerIdCXX.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "F:/Environment/cmake-3.26.3-windows-x86_64/share/cmake-3.26/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "F:/Environment/cmake-3.26.3-windows-x86_64/share/cmake-3.26/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:30 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "F:/workspace/tests/ArtAuction/ArtAuction/proj.win32/CMakeFiles/CMakeScratch/TryCompile-n1o2nm"
      binary: "F:/workspace/tests/ArtAuction/ArtAuction/proj.win32/CMakeFiles/CMakeScratch/TryCompile-n1o2nm"
    cmakeVariables:
      CMAKE_C_FLAGS: "/DWIN32 /D_WINDOWS /W3"
      CMAKE_EXE_LINKER_FLAGS: "/machine:X86"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: F:/workspace/tests/ArtAuction/ArtAuction/proj.win32/CMakeFiles/CMakeScratch/TryCompile-n1o2nm
        
        Run Build Command(s):F:/Environment/Microsoft Visual Studio/2022/MSBuild/Current/Bin/amd64/MSBuild.exe cmTC_3e26c.vcxproj /p:Configuration=Debug /p:Platform=Win32 /p:VisualStudioVersion=17.0 /v:n && MSBuild version 17.5.1+f6fdcf537 for .NET Framework
        빌드 시작: 2023-04-25 오후 12:41:30
        Included response file: F:\\Environment\\Microsoft Visual Studio\\2022\\MSBuild\\Current\\Bin\\amd64\\MSBuild.rsp
        
        1 노드의 "F:\\workspace\\tests\\ArtAuction\\ArtAuction\\proj.win32\\CMakeFiles\\CMakeScratch\\TryCompile-n1o2nm\\cmTC_3e26c.vcxproj" 프로젝트(기본 대상)입니다.
        PrepareForBuild:
          "cmTC_3e26c.dir\\Debug\\" 디렉터리를 만들고 있습니다.
          "F:\\workspace\\tests\\ArtAuction\\ArtAuction\\proj.win32\\CMakeFiles\\CMakeScratch\\TryCompile-n1o2nm\\Debug\\" 디렉터리를 만들고 있습니다.
          "cmTC_3e26c.dir\\Debug\\cmTC_3e26c.tlog\\" 디렉터리를 만들고 있습니다.
        InitializeBuildStatus:
          "AlwaysCreate"이(가) 지정되었기 때문에 "cmTC_3e26c.dir\\Debug\\cmTC_3e26c.tlog\\unsuccessfulbuild"을(를) 만들고 있습니다.
        ClCompile:
          F:\\Environment\\Microsoft Visual Studio\\2022\\VC\\Tools\\MSVC\\14.35.32215\\bin\\HostX64\\x86\\CL.exe /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /Oy- /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_3e26c.dir\\Debug\\\\" /Fd"cmTC_3e26c.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TC /analyze- /errorReport:queue "F:\\Environment\\cmake-3.26.3-windows-x86_64\\share\\cmake-3.26\\Modules\\CMakeCCompilerABI.c"
          x86용 Microsoft (R) C/C++ 최적화 컴파일러 버전 19.35.32217.1
          CMakeCCompilerABI.c
          Copyright (c) Microsoft Corporation. All rights reserved.
          cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /Oy- /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_3e26c.dir\\Debug\\\\" /Fd"cmTC_3e26c.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TC /analyze- /errorReport:queue "F:\\Environment\\cmake-3.26.3-windows-x86_64\\share\\cmake-3.26\\Modules\\CMakeCCompilerABI.c"
        Link:
          F:\\Environment\\Microsoft Visual Studio\\2022\\VC\\Tools\\MSVC\\14.35.32215\\bin\\HostX64\\x86\\link.exe /ERRORREPORT:QUEUE /OUT:"F:\\workspace\\tests\\ArtAuction\\ArtAuction\\proj.win32\\CMakeFiles\\CMakeScratch\\TryCompile-n1o2nm\\Debug\\cmTC_3e26c.exe" /INCREMENTAL /ILK:"cmTC_3e26c.dir\\Debug\\cmTC_3e26c.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"F:/workspace/tests/ArtAuction/ArtAuction/proj.win32/CMakeFiles/CMakeScratch/TryCompile-n1o2nm/Debug/cmTC_3e26c.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"F:/workspace/tests/ArtAuction/ArtAuction/proj.win32/CMakeFiles/CMakeScratch/TryCompile-n1o2nm/Debug/cmTC_3e26c.lib" /MACHINE:X86 /SAFESEH  /machine:X86 cmTC_3e26c.dir\\Debug\\CMakeCCompilerABI.obj
          cmTC_3e26c.vcxproj -> F:\\workspace\\tests\\ArtAuction\\ArtAuction\\proj.win32\\CMakeFiles\\CMakeScratch\\TryCompile-n1o2nm\\Debug\\cmTC_3e26c.exe
        FinalizeBuildStatus:
          "cmTC_3e26c.dir\\Debug\\cmTC_3e26c.tlog\\unsuccessfulbuild" 파일을 삭제하고 있습니다.
          "cmTC_3e26c.dir\\Debug\\cmTC_3e26c.tlog\\cmTC_3e26c.lastbuildstate"에 연결(touching)하고 있습니다.
        "F:\\workspace\\tests\\ArtAuction\\ArtAuction\\proj.win32\\CMakeFiles\\CMakeScratch\\TryCompile-n1o2nm\\cmTC_3e26c.vcxproj" 프로젝트를 빌드했습니다(기본 대상).
        
        빌드했습니다.
            경고 0개
            오류 0개
        
        경과 시간: 00:00:00.87
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "F:/Environment/cmake-3.26.3-windows-x86_64/share/cmake-3.26/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "F:/Environment/cmake-3.26.3-windows-x86_64/share/cmake-3.26/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:30 (project)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "F:/workspace/tests/ArtAuction/ArtAuction/proj.win32/CMakeFiles/CMakeScratch/TryCompile-1nwlgb"
      binary: "F:/workspace/tests/ArtAuction/ArtAuction/proj.win32/CMakeFiles/CMakeScratch/TryCompile-1nwlgb"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "/DWIN32 /D_WINDOWS /W3 /GR /EHsc"
      CMAKE_EXE_LINKER_FLAGS: "/machine:X86"
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: F:/workspace/tests/ArtAuction/ArtAuction/proj.win32/CMakeFiles/CMakeScratch/TryCompile-1nwlgb
        
        Run Build Command(s):F:/Environment/Microsoft Visual Studio/2022/MSBuild/Current/Bin/amd64/MSBuild.exe cmTC_40aec.vcxproj /p:Configuration=Debug /p:Platform=Win32 /p:VisualStudioVersion=17.0 /v:n && MSBuild version 17.5.1+f6fdcf537 for .NET Framework
        빌드 시작: 2023-04-25 오후 12:41:32
        Included response file: F:\\Environment\\Microsoft Visual Studio\\2022\\MSBuild\\Current\\Bin\\amd64\\MSBuild.rsp
        
        1 노드의 "F:\\workspace\\tests\\ArtAuction\\ArtAuction\\proj.win32\\CMakeFiles\\CMakeScratch\\TryCompile-1nwlgb\\cmTC_40aec.vcxproj" 프로젝트(기본 대상)입니다.
        PrepareForBuild:
          "cmTC_40aec.dir\\Debug\\" 디렉터리를 만들고 있습니다.
          "F:\\workspace\\tests\\ArtAuction\\ArtAuction\\proj.win32\\CMakeFiles\\CMakeScratch\\TryCompile-1nwlgb\\Debug\\" 디렉터리를 만들고 있습니다.
          "cmTC_40aec.dir\\Debug\\cmTC_40aec.tlog\\" 디렉터리를 만들고 있습니다.
        InitializeBuildStatus:
          "AlwaysCreate"이(가) 지정되었기 때문에 "cmTC_40aec.dir\\Debug\\cmTC_40aec.tlog\\unsuccessfulbuild"을(를) 만들고 있습니다.
        ClCompile:
          F:\\Environment\\Microsoft Visual Studio\\2022\\VC\\Tools\\MSVC\\14.35.32215\\bin\\HostX64\\x86\\CL.exe /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /Oy- /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_40aec.dir\\Debug\\\\" /Fd"cmTC_40aec.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TP /analyze- /errorReport:queue "F:\\Environment\\cmake-3.26.3-windows-x86_64\\share\\cmake-3.26\\Modules\\CMakeCXXCompilerABI.cpp"
          x86용 Microsoft (R) C/C++ 최적화 컴파일러 버전 19.35.32217.1
          CMakeCXXCompilerABI.cpp
          Copyright (c) Microsoft Corporation. All rights reserved.
          cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /Oy- /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_40aec.dir\\Debug\\\\" /Fd"cmTC_40aec.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TP /analyze- /errorReport:queue "F:\\Environment\\cmake-3.26.3-windows-x86_64\\share\\cmake-3.26\\Modules\\CMakeCXXCompilerABI.cpp"
        Link:
          F:\\Environment\\Microsoft Visual Studio\\2022\\VC\\Tools\\MSVC\\14.35.32215\\bin\\HostX64\\x86\\link.exe /ERRORREPORT:QUEUE /OUT:"F:\\workspace\\tests\\ArtAuction\\ArtAuction\\proj.win32\\CMakeFiles\\CMakeScratch\\TryCompile-1nwlgb\\Debug\\cmTC_40aec.exe" /INCREMENTAL /ILK:"cmTC_40aec.dir\\Debug\\cmTC_40aec.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"F:/workspace/tests/ArtAuction/ArtAuction/proj.win32/CMakeFiles/CMakeScratch/TryCompile-1nwlgb/Debug/cmTC_40aec.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"F:/workspace/tests/ArtAuction/ArtAuction/proj.win32/CMakeFiles/CMakeScratch/TryCompile-1nwlgb/Debug/cmTC_40aec.lib" /MACHINE:X86 /SAFESEH  /machine:X86 cmTC_40aec.dir\\Debug\\CMakeCXXCompilerABI.obj
          cmTC_40aec.vcxproj -> F:\\workspace\\tests\\ArtAuction\\ArtAuction\\proj.win32\\CMakeFiles\\CMakeScratch\\TryCompile-1nwlgb\\Debug\\cmTC_40aec.exe
        FinalizeBuildStatus:
          "cmTC_40aec.dir\\Debug\\cmTC_40aec.tlog\\unsuccessfulbuild" 파일을 삭제하고 있습니다.
          "cmTC_40aec.dir\\Debug\\cmTC_40aec.tlog\\cmTC_40aec.lastbuildstate"에 연결(touching)하고 있습니다.
        "F:\\workspace\\tests\\ArtAuction\\ArtAuction\\proj.win32\\CMakeFiles\\CMakeScratch\\TryCompile-1nwlgb\\cmTC_40aec.vcxproj" 프로젝트를 빌드했습니다(기본 대상).
        
        빌드했습니다.
            경고 0개
            오류 0개
        
        경과 시간: 00:00:00.92
        
      exitCode: 0
...
